### ISSUE TITLE
No repository was found.

### ISSUE THREAD

**Issue by sGambolati** [lukeautry/ts-app#2]
I'm facing an issue when trying to retrieve a repository using the `getRepository` method from *typeorm* in a new controller.

Error message is:
```json
{
    "message": "No repository for \"User\" was found. Looks like this entity is not registered in current \"default\" connection?",
    "name": "RepositoryNotFoundError",
    "status": 500
}
```

Following the User entity sample, I've created a controller (see below) and I have the given error message.
I checked that the *entities* entry in _ormconfig.js_ is right setted to [`${__dirname}/api/database/entities/*.ts`]. 
Can you provide a working sample to retrieve data from typeorm repository?

Thanks!

**Comment by lukeautry** [comment]
@sGambolati I've seen this happen when `getRepository` is called before the typeorm connection is initialized. 

Check out this issue: https://github.com/typeorm/typeorm/issues/682

**Comment by sGambolati** [comment]
Finally, I've solved the issue retrieving entity's repository as `
getRepository("User")`.
