### ISSUE TITLE
Can't install with command "yarn"

### ISSUE THREAD

**Issue by MaximeTroiano** [lukeautry/ts-app#3]
I cannot make this repository download all the necessary packages when using the command "yarn".

The error I get is when the process is trying to install the package "node-sass".
Output log:

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Code\Projects\MYPROJECT\MYPROJECT-tests\ts-app\node_modules\node-sass\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Code\\Projects\\MYPROJECT\\MYPROJECT-tests\\ts-app\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Code\Projects\MYPROJECT\MYPROJECT-tests\ts-app\node_modules\node-sass
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by MaximeTroiano** [comment]
By removing the dependency and re-installing it, it is fixed.

**Comment by waynebloss** [comment]
Same here - on Manjaro Linux. First time I ran `yarn install` it failed to build `node-sass`. Running `yarn remove node-sass`, then `yarn add node-sass` fixed it.

I'm betting that the author of this package has a lock file that was generated on a different platform, perhaps a Mac.
